### ISSUE TITLE
Change snyk to run `test` on PR's and `monitor` on merges.

### ISSUE THREAD

**Issue by zfouts** [rstudio/rstudio-docker-products#393]
Snyk does not need to run on every single commit - only on specific commits or merge to main.

Two choices to consider:

Change to scan only on merge to main branch by default, but also add additional method to scan on-demand via label for testing.
https://github.com/marketplace/actions/label-actions

Change to ignore "draft" mode PR's using something like:
```YAML
on:
  pull_request:
    types: [review_requested, ready_for_review]
```
or

```YAML
if: github.event.pull_request.draft == false
```
or a combo of the two
